### ISSUE TITLE
Link to labs (HTML format) didn't link to the zh.cn version

### ISSUE THREAD

**Issue by lettucebo** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions.zh-cn#2]
### Contact Details

Money.Yu@microsoft.com

### What happened?

Readme.md

Description of issue:
The link is being redirect to the English version, not the zn.cn version

Repro steps:

![2023-04-17_17-11-49](https://user-images.githubusercontent.com/891383/232440207-fd0c965e-dd07-475b-abef-ca1d88c3fa34.gif)

### Lab

Other

### Relevant screenshots

![2023-04-17_17-11-49](https://user-images.githubusercontent.com/891383/232440207-fd0c965e-dd07-475b-abef-ca1d88c3fa34.gif)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
In discussion with the WWL team

**Comment by chriscarty00** [comment]
Still repro - has been reported to WWL team

**Comment by stonezy123** [comment]
This is by-design using the en-us link.
